In [1]:
pip install nltk

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 531.8 kB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.8/281.8 kB 268.0 kB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 447.6 kB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 634.5 kB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [3]:
import nltk

In [6]:
# import nltk
# import ssl

# try:
#     _create_unverified_https_context = ssl._create_unverified_context
# except AttributeError:
#     pass
# else:
#     ssl._create_default_https_context = _create_unverified_https_context

# nltk.download("popular")

[nltk_data] Downloading collection 'popular'
[nltk_data]    | 
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     /Users/mikolajmiecznikowski/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     /Users/mikolajmiecznikowski/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     /Users/mikolajmiecznikowski/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     /Users/mikolajmiecznikowski/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     /Users/mikolajmiecznikowski/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /Users/m

True

In [9]:
from bs4 import BeautifulSoup
import numpy as np

wiki = "http://en.wikipedia.org/wiki/"
titles = ["Integral", "Riemann_integral", "Riemann-Stieltjes_integral", "Derivative",
    "Limit_of_a_sequence", "Edvard_Munch", "Vincent_van_Gogh", "Jan_Matejko",
    "Lev_Tolstoj", "Franz_Kafka", "J._R._R._Tolkien"]

from urllib.request import urlopen

def parse(url):        
    x = urlopen(url).read()
    x = BeautifulSoup(x).find("div",id="bodyContent").find_all("p")
    return(x)

articles = [parse(url) for url in [wiki+x for x in titles]]
articles = [" ".join([str(paragraph) for paragraph in article]) for article in articles]

articles[0][:200]

'<p>In <a href="/wiki/Mathematics" title="Mathematics">mathematics</a>, an <b>integral</b> assigns numbers to functions in a way that describes displacement, <a href="/wiki/Area" title="Area">area</a>,'

In [ ]:
import re

In [12]:
articles = [re.sub("<.+?>"," ",art) for art in articles]
articles[0][:500]

' In  mathematics , an  integral  assigns numbers to functions in a way that describes displacement,  area ,  volume , and other concepts that arise by combining  infinitesimal  data. The process of finding integrals is called  integration . Along with  differentiation , integration is a fundamental, essential operation of  calculus ,  [a]   and serves as a tool to solve problems in mathematics and  physics  involving the area of an arbitrary shape, the length of a curve, and the volume of a soli'

In [15]:
articles = [art.lower() for art in articles]
articles[0][:5000]

" in  mathematics , an  integral  assigns numbers to functions in a way that describes displacement,  area ,  volume , and other concepts that arise by combining  infinitesimal  data. the process of finding integrals is called  integration . along with  differentiation , integration is a fundamental, essential operation of  calculus ,  [a]   and serves as a tool to solve problems in mathematics and  physics  involving the area of an arbitrary shape, the length of a curve, and the volume of a solid, among others.\n   the integrals enumerated here are those termed  definite integrals , which can be interpreted as the signed  area  of the region in the plane that is bounded by the  graph  of a given  function  between two points in the  real line . conventionally, areas above the horizontal axis of the plane are positive while areas below are negative. integrals also refer to the concept of an  antiderivative , a function whose derivative is the given function. in this case, they are call

In [ ]:
?nltk.word_tokenize

In [17]:
?nltk.TreebankWordTokenizer

Init signature: nltk.TreebankWordTokenizer()
Docstring:     
The Treebank tokenizer uses regular expressions to tokenize text as in Penn Treebank.

This tokenizer performs the following steps:

- split standard contractions, e.g. ``don't`` -> ``do n't`` and ``they'll`` -> ``they 'll``
- treat most punctuation characters as separate tokens
- split off commas and single quotes, when followed by whitespace
- separate periods that appear at the end of line

>>> from nltk.tokenize import TreebankWordTokenizer
>>> s = '''Good muffins cost $3.88\nin New York.  Please buy me\ntwo of them.\nThanks.'''
>>> TreebankWordTokenizer().tokenize(s)
['Good', 'muffins', 'cost', '$', '3.88', 'in', 'New', 'York.', 'Please', 'buy', 'me', 'two', 'of', 'them.', 'Thanks', '.']
>>> s = "They'll save and invest more."
>>> TreebankWordTokenizer().tokenize(s)
['They', "'ll", 'save', 'and', 'invest', 'more', '.']
>>> s = "hi, my name can't hello,"
>>> TreebankWordTokenizer().tokenize(s)
['hi', ',', 'my', 'name', 'c

In [ ]:
# można usunąć przypisy regexem

In [ ]:
# rozbicie tekstów na tokeny

In [19]:
articles = [nltk.word_tokenize(art) for art in articles]
articles[0][:10]

['in',
 'mathematics',
 ',',
 'an',
 'integral',
 'assigns',
 'numbers',
 'to',
 'functions',
 'in']

In [ ]:
# usuwanie stopwords

In [25]:
stopwords = set(nltk.corpus.stopwords.words("english")) # mozna tokenizowac stopwordsy
articles = [[word for word in art if word not in stopwords] for art in articles]
articles[0][:10]

['mathematics',
 ',',
 'integral',
 'assigns',
 'numbers',
 'functions',
 'way',
 'describes',
 'displacement',
 ',']

In [ ]:
# stemming

In [29]:
#Liczba unikalnych slow przed stemmowaniem:
len(set(articles[0]))

1185

In [28]:
stemmer = nltk.PorterStemmer()
stemmer.stem("mathematically")

'mathemat'

In [30]:
articles = [[stemmer.stem(word) for word in art] for art in articles]

In [31]:
len(set(articles[0]))

942

In [32]:
articles[0]

['mathemat',
 ',',
 'integr',
 'assign',
 'number',
 'function',
 'way',
 'describ',
 'displac',
 ',',
 'area',
 ',',
 'volum',
 ',',
 'concept',
 'aris',
 'combin',
 'infinitesim',
 'data',
 '.',
 'process',
 'find',
 'integr',
 'call',
 'integr',
 '.',
 'along',
 'differenti',
 ',',
 'integr',
 'fundament',
 ',',
 'essenti',
 'oper',
 'calculu',
 ',',
 '[',
 ']',
 'serv',
 'tool',
 'solv',
 'problem',
 'mathemat',
 'physic',
 'involv',
 'area',
 'arbitrari',
 'shape',
 ',',
 'length',
 'curv',
 ',',
 'volum',
 'solid',
 ',',
 'among',
 'other',
 '.',
 'integr',
 'enumer',
 'term',
 'definit',
 'integr',
 ',',
 'interpret',
 'sign',
 'area',
 'region',
 'plane',
 'bound',
 'graph',
 'given',
 'function',
 'two',
 'point',
 'real',
 'line',
 '.',
 'convent',
 ',',
 'area',
 'horizont',
 'axi',
 'plane',
 'posit',
 'area',
 'neg',
 '.',
 'integr',
 'also',
 'refer',
 'concept',
 'antideriv',
 ',',
 'function',
 'whose',
 'deriv',
 'given',
 'function',
 '.',
 'case',
 ',',
 'call',
 'in

In [ ]:
# usuwanie interpunkcji

In [33]:
articles = [" ".join(art) for art in articles]
articles[0]

In [35]:
import string
table = str.maketrans({key: None for key in string.punctuation})
articles = [a.translate(table) for a in articles]

In [37]:
articles[0]

'mathemat  integr assign number function way describ displac  area  volum  concept aris combin infinitesim data  process find integr call integr  along differenti  integr fundament  essenti oper calculu    serv tool solv problem mathemat physic involv area arbitrari shape  length curv  volum solid  among other  integr enumer term definit integr  interpret sign area region plane bound graph given function two point real line  convent  area horizont axi plane posit area neg  integr also refer concept antideriv  function whose deriv given function  case  call indefinit integr  fundament theorem calculu relat definit integr differenti provid method comput definit integr function antideriv known  although method calcul area volum date ancient greek mathemat  principl integr formul independ isaac newton gottfri wilhelm leibniz late 17th centuri  thought area curv infinit sum rectangl infinitesim width  bernhard riemann later gave rigor definit integr  base limit procedur approxim area curvil

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

In [39]:
?CountVectorizer

Init signature:
CountVectorizer(
    *,
    input='content',
    encoding='utf-8',
    decode_error='strict',
    strip_accents=None,
    lowercase=True,
    preprocessor=None,
    tokenizer=None,
    stop_words=None,
    token_pattern='(?u)\\b\\w\\w+\\b',
    ngram_range=(1, 1),
    analyzer='word',
    max_df=1.0,
    min_df=1,
    max_features=None,
    vocabulary=None,
    binary=False,
    dtype=<class 'numpy.int64'>,
)
Docstring:     
Convert a collection of text documents to a matrix of token counts.

This implementation produces a sparse representation of the counts using
scipy.sparse.csr_matrix.

If you do not provide an a-priori dictionary and you do not use an analyzer
that does some kind of feature selection then the number of features will
be equal to the vocabulary size found by analyzing the data.

Read more in the :ref:`User Guide <text_feature_extraction>`.

Parameters
----------
input : {'filename', 'file', 'content'}, default='content'
    - If `'filename'`, the sequ

In [45]:
vectorizer = CountVectorizer(token_pattern='(?u)\\b\\w\\w+\\b', min_df=3)
vectorizer.fit(articles)
X = vectorizer.transform(articles)
X

<11x1558 sparse matrix of type '<class 'numpy.int64'>'
	with 7206 stored elements in Compressed Sparse Row format>

In [46]:
vectorizer.get_feature_names()

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['10',
 '100',
 '101',
 '102',
 '103',
 '104',
 '105',
 '106',
 '107',
 '108',
 '109',
 '11',
 '110',
 '111',
 '112',
 '113',
 '114',
 '115',
 '116',
 '117',
 '118',
 '119',
 '12',
 '120',
 '121',
 '122',
 '123',
 '124',
 '125',
 '126',
 '127',
 '128',
 '129',
 '13',
 '130',
 '131',
 '132',
 '133',
 '134',
 '135',
 '136',
 '14',
 '140',
 '141',
 '142',
 '147',
 '148',
 '149',
 '15',
 '150',
 '151',
 '152',
 '155',
 '156',
 '157',
 '158',
 '159',
 '16',
 '160',
 '161',
 '162',
 '163',
 '164',
 '165',
 '166',
 '167',
 '168',
 '169',
 '17',
 '170',
 '171',
 '172',
 '173',
 '174',
 '175',
 '176',
 '177',
 '178',
 '179',
 '18',
 '180',
 '181',
 '1819',
 '182',
 '183',
 '184',
 '185',
 '1851',
 '1854',
 '1857',
 '186',
 '1860',
 '1861',
 '1862',
 '1863',
 '1864',
 '1868',
 '1869',
 '187',
 '1870',
 '1872',
 '1874',
 '1877',
 '1878',
 '1879',
 '188',
 '1882',
 '1883',
 '1884',
 '1886',
 '1887',
 '1889',
 '189',
 '1890',
 '1891',
 '1892',
 '1893',
 '1894',
 '1895',
 '1896',
 '1898',
 '19',
 '1

In [ ]:
# warto zrupowac np. wzgledem liczby cyfr

In [47]:
X[3,5]

0

In [48]:
X[3]

<1x1558 sparse matrix of type '<class 'numpy.int64'>'
	with 365 stored elements in Compressed Sparse Row format>

In [49]:
X[:,3]

<11x1 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [50]:
X[:,3].todense()

matrix([[0],
        [0],
        [0],
        [0],
        [0],
        [2],
        [1],
        [0],
        [0],
        [1],
        [1]])

In [51]:
X[:,3].A.flatten()

array([0, 0, 0, 0, 0, 2, 1, 0, 0, 1, 1])

In [53]:
X[:,vectorizer.get_feature_names().index("paint")].todense()

matrix([[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [ 68],
        [125],
        [ 20],
        [  0],
        [  0],
        [  4]])

In [54]:
# Podaj 10 najczestszych slow z kazdego dokumentu argsort

In [115]:
i = 0
n = 10


vectorizer = CountVectorizer(token_pattern='(?u)\\b\\w\\w+\\b', min_df=3)
vectorizer.fit(articles)
X = vectorizer.transform(articles)

words = np.array(vectorizer.get_feature_names())
for i in range(X.shape[0]):
    print(words[X[i].A.flatten().argsort()[::-1]][:n])

['integr' 'function' 'use' 'area' 'interv' 'sum' 'riemann' 'one'
 'differenti' 'definit']
['integr' 'riemann' 'function' 'sum' 'interv' 'partit' 'tag' 'zero'
 'point' 'definit']
['integr' 'displaystyl' 'riemann' 'function' 'gener' 'partit' 'continu'
 'respect' 'bound' 'exist']
['deriv' 'function' 'point' 'vector' 'differenti' 'linear' 'variabl'
 'direct' 'displaystyl' 'approxim']
['displaystyl' 'sequenc' 'limit' 'to' 'space' 'gt' 'seri' 'right' 'exist'
 'real']
['paint' 'museum' 'work' 'art' 'life' 'exhibit' 'oil' 'artist' 'includ'
 'canva']
['paint' 'work' 'art' 'museum' 'pari' 'artist' 'two' '1890' '1889' 'life']
['paint' 'art' 'histor' 'nation' '30' 'work' 'fine' 'histori' '17'
 'museum']
['work' 'war' 'also' 'wrote' 'novel' 'state' 'one' 'peac' 'time' 'life']
['work' 'publish' 'stori' 'write' 'german' 'der' 'franz' 'die' 'time'
 'first']
['work' 'languag' 'english' 'publish' 'later' 'book' 'first' 'letter'
 'year' 'stori']


In [81]:
ind

array([ 541,  570, 1086, 1265, 1401,  887,  318, 1489,  759,  878])

In [110]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [119]:
i = 0
n = 7


vectorizer = TfidfVectorizer(token_pattern='(?u)\\b\\w\\w+\\b', min_df=3)
vectorizer.fit(articles)
X = vectorizer.transform(articles)

words = np.array(vectorizer.get_feature_names())
for i in range(X.shape[0]):
    print(words[X[i].A.flatten().argsort()[::-1]][:n])

['integr' 'function' 'interv' 'riemann' 'area' 'differenti' 'sum']
['integr' 'riemann' 'interv' 'partit' 'sum' 'function' 'tag']
['integr' 'riemann' 'displaystyl' 'function' 'partit' 'bound' 'gener']
['deriv' 'function' 'vector' 'differenti' 'variabl' 'linear' 'displaystyl']
['displaystyl' 'sequenc' 'limit' 'to' 'gt' 'space' 'tend']
['paint' 'museum' 'art' 'oil' 'work' 'life' 'canva']
['paint' 'work' 'art' 'museum' 'pari' 'portrait' '1889']
['paint' 'histor' 'art' 'fine' 'nation' '30' 'histori']
['war' 'work' 'novel' 'wrote' 'peac' 'also' 'life']
['work' 'stori' 'franz' 'publish' 'der' 'literari' 'jewish']
['english' 'languag' 'work' 'colleg' 'stori' 'publish' 'year']


In [150]:
from sklearn.datasets import fetch_20newsgroups

In [160]:
categories = ['alt.atheism', 'talk.religion.misc', 'comp.graphics', 'sci.space']
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories)

In [181]:
texts = newsgroups_train.data
y = newsgroups_train.target

stemmer = nltk.PorterStemmer()
texts = [nltk.word_tokenize(mail) for mail in texts]
texts = [[stemmer.stem(word) for word in mail] for mail in texts]
texts = [" ".join(mail) for mail in texts]

i = 0
n = 7


vectorizer = TfidfVectorizer(token_pattern='(?u)\\b\\w\\w+\\b', min_df=1)
vectorizer.fit(texts)
X = vectorizer.transform(texts)

words = np.array(vectorizer.get_feature_names())
for i in range(2):#X.shape[0]):
    print(words[X[i].A.flatten().argsort()[::-1]][:n])

['rych' 'prj' 'file' 'textur' '3d' 'festival' 'save']
['almanac' 'frog' 'koresh' '245' '604' 'uta' 'utarlg']


In [182]:
from sklearn.decomposition import TruncatedSVD

In [189]:
vectorizer = TfidfVectorizer(token_pattern='(?u)\\b\\w\\w+\\b', min_df=1)
vectorizer.fit(articles)
X = vectorizer.transform(articles)

In [190]:
dim_reductor = TruncatedSVD(3)
dim_reductor.fit(X)
dim_reductor.transform(X).round(2)

array([[ 0.86, -0.04, -0.1 ],
       [ 0.85, -0.06, -0.14],
       [ 0.89, -0.07, -0.01],
       [ 0.47,  0.03,  0.16],
       [ 0.37,  0.02,  0.31],
       [ 0.04,  0.55, -0.36],
       [ 0.05,  0.58, -0.33],
       [ 0.04,  0.56, -0.22],
       [ 0.04,  0.36,  0.43],
       [ 0.05,  0.37,  0.47],
       [ 0.05,  0.38,  0.42]])

In [1]:
def f1(list_of_list):
    result = []
    for inner_list in list_of_list:
        for x in inner_list:
            if x not in result:
                result.append(x)
    return result

def f2(list_of_list):
    flat_list = []
    for inner_list in list_of_list:
        flat_list.extend(inner_list)
    return [
        x for i, x in enumerate(flat_list)
        if flat_list.index(x) == i]

def f3(list_of_list):
    result = []
    seen = set()
    for inner_list in list_of_list:
        for x in inner_list:
            if x not in seen:
                result.append(x)
                seen.add(x)
    return result

In [2]:
exlst = [10000*[1,4,6,1,1,2,1,1]]

In [3]:
%%time
f1(exlst)

CPU times: user 2.76 ms, sys: 29 µs, total: 2.79 ms
Wall time: 2.89 ms


[1, 4, 6, 2]

In [4]:
%%time
f2(exlst)

CPU times: user 7.13 ms, sys: 125 µs, total: 7.26 ms
Wall time: 7.24 ms


[1, 4, 6, 2]

In [5]:
%%time
f3(exlst)

CPU times: user 1.53 ms, sys: 0 ns, total: 1.53 ms
Wall time: 1.53 ms


[1, 4, 6, 2]

In [6]:
1.2 - 1.1

0.09999999999999987

In [7]:
class BaseLayer:
    def __init__(self, name=""):
        self.name = name

    def __repr__(self):
        return f"{self.name}Layer"

class ActivationLayer(BaseLayer):
    def __init__(self, size):
        super().__init__("Activation")
        self.size = size

class FCLayer(BaseLayer):
    def __init__(self, size):
        super().__init__("FullyConnected")
        self.size = size

In [8]:
BaseLayer()

Layer