In [4]:
from google.colab import drive
drive.mount('/content/gdrive')


Mounted at /content/gdrive


In [5]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [6]:
data=pd.read_csv('gdrive/My Drive/DS Bootcamp 14-15.05/pliki/ex1data2.txt', header=None)

In [7]:
data.columns = ['feet','band','price']

In [8]:
data.head()

feet  band   price
0  2104     3  399900
1  1600     3  329900
2  2400     3  369000
3  1416     2  232000
4  3000     4  539900

In [33]:
X= data.iloc[:, 0:1]
y= data['price']

In [10]:
X.head()

feet  band
0  2104     3
1  1600     3
2  2400     3
3  1416     2
4  3000     4

In [11]:
y.values[:5]

array([399900, 329900, 369000, 232000, 539900])

In [12]:
poly = PolynomialFeatures(degree=8)
X_poly = poly.fit_transform(X)

In [13]:
X_poly[:5]

array([[1.00000000e+00, 2.10400000e+03, 3.00000000e+00, 4.42681600e+06,
        6.31200000e+03, 9.00000000e+00, 9.31402086e+09, 1.32804480e+07,
        1.89360000e+04, 2.70000000e+01, 1.95966999e+13, 2.79420626e+10,
        3.98413440e+07, 5.68080000e+04, 8.10000000e+01, 4.12314566e+16,
        5.87900997e+13, 8.38261878e+10, 1.19524032e+08, 1.70424000e+05,
        2.43000000e+02, 8.67509847e+19, 1.23694370e+17, 1.76370299e+14,
        2.51478563e+11, 3.58572096e+08, 5.11272000e+05, 7.29000000e+02,
        1.82524072e+23, 2.60252954e+20, 3.71083109e+17, 5.29110897e+14,
        7.54435690e+11, 1.07571629e+09, 1.53381600e+06, 2.18700000e+03,
        3.84030647e+26, 5.47572215e+23, 7.80758862e+20, 1.11324933e+18,
        1.58733269e+15, 2.26330707e+12, 3.22714886e+09, 4.60144800e+06,
        6.56100000e+03],
       [1.00000000e+00, 1.60000000e+03, 3.00000000e+00, 2.56000000e+06,
        4.80000000e+03, 9.00000000e+00, 4.09600000e+09, 7.68000000e+06,
        1.44000000e+04, 2.70000000e+01,

In [14]:
model = LinearRegression(fit_intercept=True)
model.fit(X_poly,y)

LinearRegression()

In [15]:
model.score(X_poly, y)

0.810216500428273

In [16]:
model.intercept_

183213.67736899914

In [17]:
model.coef_ 

array([ 1.56376702e-11,  7.75424153e-11,  5.35322860e-15,  4.26877816e-16,
       -3.01903799e-20,  1.32016593e-19, -3.82612512e-15, -2.25226204e-17,
       -7.74174314e-20, -2.15158790e-22, -2.04229726e-12, -2.07039376e-14,
       -9.10106177e-17, -2.94527416e-19, -8.01154369e-22,  6.86824706e-11,
       -1.14703017e-11, -8.34264397e-14, -3.46065082e-16, -1.09891702e-18,
       -2.97692110e-21, -1.67286626e-13,  9.50219151e-11, -4.71023461e-11,
       -3.23126876e-13, -1.30747001e-15, -4.10932432e-18, -1.11142994e-20,
        2.38892318e-17,  5.18885747e-14, -5.07216725e-11, -1.89818252e-10,
       -1.25050916e-12, -4.96773928e-15, -1.54939955e-17, -4.18689464e-20,
       -3.90743319e-21,  5.19442453e-18, -1.41196120e-14,  1.08364939e-11,
       -7.55239667e-10, -4.84901911e-12, -1.90114276e-14, -5.89645414e-17,
       -1.59278022e-19])

In [18]:
data.head()

feet  band   price
0  2104     3  399900
1  1600     3  329900
2  2400     3  369000
3  1416     2  232000
4  3000     4  539900

In [19]:
data.corr(method='pearson')

feet      band     price
feet   1.000000  0.559967  0.854988
band   0.559967  1.000000  0.442261
price  0.854988  0.442261  1.000000

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_poly_train, X_poly_test, y_train, y_test = train_test_split(X_poly,y, test_size=0.2, random_state=42)

In [22]:
model.fit(X_poly_train, y_train)

LinearRegression()

In [23]:
model.score(X_poly_train, y_train)

0.8657967684818111

In [24]:
model.score(X_poly_test,y_test)

-778.4006444204126

In [25]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error

In [26]:
y_pred = model.predict(X_poly_train)

In [27]:
mean_absolute_percentage_error(y_train, y_pred)

0.10946445411655095

In [28]:
y_pred = model.predict(X_poly_test)

In [29]:
mean_absolute_percentage_error(y_test, y_pred)

2.3848102381889005

In [30]:
from sklearn.base import (
    TransformerMixin, 
    BaseEstimator
)
class BoxCoxTransformer(BaseEstimator, TransformerMixin):
    fitted_lambda: float

    def fit(self, x: np.array) -> 'BoxCoxTransformer':

        _, self.fitted_lambda = stats.boxcox(x)
        return self

    def transform(self, x: np.array) -> np.array:
        # Note that for x of length = 1 stats.boxcox will raise error
        return stats.boxcox(x, self.fitted_lambda)
        

In [55]:
from sklearn.model_selection import train_test_split
from scipy import stats

X_train, X_test, y_train, y_test = train_test_split(X['feet'] , y, test_size=.2, shuffle=True)
transformer = BoxCoxTransformer().fit(X_train)
X_train_transformed = transformer.transform(X_train)
X_test_transformed = transformer.transform(X_test)

In [57]:
model1 = LinearRegression(fit_intercept=True)

model1.fit(X_train_transformed.reshape(-1,1), y_train)

LinearRegression()

In [58]:
y_pred = model1.predict(X_train_transformed.reshape(-1,1))

In [59]:
mean_absolute_error(y_train, y_pred)

54434.85956819049

In [60]:
y_pred_test = model1.predict(X_test_transformed.reshape(-1,1))
mean_absolute_error(y_test, y_pred_test)

62965.81474392116

In [62]:
print(model1.score(X_train_transformed.reshape(-1,1), y_train))
print(model1.score(X_test_transformed.reshape(-1,1),y_test))

0.5993793054194193
0.8054714656109759
