In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
!ls


Mounted at /content/gdrive
gdrive	sample_data


In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
data = pd.read_csv(('gdrive/My Drive/ex1data2.txt'), header=None)

In [ ]:
data.columns = ['feet','band','price']

In [ ]:
data.head()

feet  band   price
0  2104     3  399900
1  1600     3  329900
2  2400     3  369000
3  1416     2  232000
4  3000     4  539900

In [ ]:
X= data.iloc[:, 0:1]
y= data['price']

In [ ]:
X.values[:5]

array([[2104],
       [1600],
       [2400],
       [1416],
       [3000]])

In [ ]:
y.values[:5]

array([399900, 329900, 369000, 232000, 539900])

In [ ]:
poly = PolynomialFeatures(degree=9)
X_poly = poly.fit_transform(X)

In [ ]:
X_poly[:5]

In [ ]:
model = LinearRegression()
model.fit(X_poly,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.score(X_poly, y)

0.7584522901857944

In [ ]:
model.intercept_

247691.86613939327

In [ ]:
model.coef_ 

array([ 0.00000000e+00, -6.72396378e-18,  4.72887867e-23,  1.62222378e-24,
        2.82921368e-21,  3.85829955e-18,  3.28127192e-15, -1.34862458e-18,
        1.07591809e-22,  7.30567320e-27])

In [ ]:
data.head()

feet  band   price
0  2104     3  399900
1  1600     3  329900
2  2400     3  369000
3  1416     2  232000
4  3000     4  539900

In [ ]:
data.corr(method='pearson')

feet      band     price
feet   1.000000  0.559967  0.854988
band   0.559967  1.000000  0.442261
price  0.854988  0.442261  1.000000

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_poly_train, X_poly_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [ ]:
model.fit(X_poly_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.score(X_poly_train, y_train)

0.7633332190114398

In [ ]:
model.score(X_poly_test,y_test)

0.526301453884142

In [ ]:
from sklearn.metrics import mean_absolute_error

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
mean_absolute_error(y_test, y_pred)

69978.50296543419

In [ ]:
y_pred = model.predict(X_train)

In [ ]:
mean_absolute_error(y_train, y_pred)

46064.43314625008