In [ ]:
#!pip install nltk

In [ ]:
#nltk.download("popular")

In [1]:
import nltk
from bs4 import BeautifulSoup
import numpy as np

wiki = "http://en.wikipedia.org/wiki/"
titles = ["Integral", "Riemann_integral", "Riemann-Stieltjes_integral", "Derivative",
    "Limit_of_a_sequence", "Edvard_Munch", "Vincent_van_Gogh", "Jan_Matejko",
    "Lev_Tolstoj", "Franz_Kafka", "J._R._R._Tolkien"]

from urllib.request import urlopen

def parse(url):        
    x = urlopen(url).read()
    x = BeautifulSoup(x).find("div",id="bodyContent").find_all("p")
    return(x)

articles = [parse(url) for url in [wiki+x for x in titles]]
articles = [" ".join([str(paragraph) for paragraph in article]) for article in articles]

articles[0][:200]

'<p>In <a href="/wiki/Mathematics" title="Mathematics">mathematics</a>, an <b>integral</b> assigns numbers to functions in a way that describes displacement, <a href="/wiki/Area" title="Area">area</a>,'

In [6]:
import re
articles = [re.sub("<.+?>"," ", art) for art in articles]
articles[0][:500]

' In  mathematics , an  integral  assigns numbers to functions in a way that describes displacement,  area ,  volume , and other concepts that arise by combining  infinitesimal  data. The process of finding integrals is called  integration . Along with  differentiation , integration is a fundamental, essential operation of  calculus ,  [a]   and serves as a tool to solve problems in mathematics and  physics  involving the area of an arbitrary shape, the length of a curve, and the volume of a soli'

In [7]:
articles[0]

' In  mathematics , an  integral  assigns numbers to functions in a way that describes displacement,  area ,  volume , and other concepts that arise by combining  infinitesimal  data. The process of finding integrals is called  integration . Along with  differentiation , integration is a fundamental, essential operation of  calculus ,  [a]   and serves as a tool to solve problems in mathematics and  physics  involving the area of an arbitrary shape, the length of a curve, and the volume of a solid, among others.\n   The integrals enumerated here are those termed  definite integrals , which can be interpreted as the signed  area  of the region in the plane that is bounded by the  graph  of a given  function  between two points in the  real line . Conventionally, areas above the horizontal axis of the plane are positive while areas below are negative. Integrals also refer to the concept of an  antiderivative , a function whose derivative is the given function. In this case, they are call

In [ ]:
# moża jeszcze usunac przypisów regexem

In [8]:
articles = [art.lower() for art in articles]
articles[0][:500]

' in  mathematics , an  integral  assigns numbers to functions in a way that describes displacement,  area ,  volume , and other concepts that arise by combining  infinitesimal  data. the process of finding integrals is called  integration . along with  differentiation , integration is a fundamental, essential operation of  calculus ,  [a]   and serves as a tool to solve problems in mathematics and  physics  involving the area of an arbitrary shape, the length of a curve, and the volume of a soli'

In [10]:
articles[0]

' in  mathematics , an  integral  assigns numbers to functions in a way that describes displacement,  area ,  volume , and other concepts that arise by combining  infinitesimal  data. the process of finding integrals is called  integration . along with  differentiation , integration is a fundamental, essential operation of  calculus ,  [a]   and serves as a tool to solve problems in mathematics and  physics  involving the area of an arbitrary shape, the length of a curve, and the volume of a solid, among others.\n   the integrals enumerated here are those termed  definite integrals , which can be interpreted as the signed  area  of the region in the plane that is bounded by the  graph  of a given  function  between two points in the  real line . conventionally, areas above the horizontal axis of the plane are positive while areas below are negative. integrals also refer to the concept of an  antiderivative , a function whose derivative is the given function. in this case, they are call

In [11]:
nltk.word_tokenize(articles[0])

['in',
 'mathematics',
 ',',
 'an',
 'integral',
 'assigns',
 'numbers',
 'to',
 'functions',
 'in',
 'a',
 'way',
 'that',
 'describes',
 'displacement',
 ',',
 'area',
 ',',
 'volume',
 ',',
 'and',
 'other',
 'concepts',
 'that',
 'arise',
 'by',
 'combining',
 'infinitesimal',
 'data',
 '.',
 'the',
 'process',
 'of',
 'finding',
 'integrals',
 'is',
 'called',
 'integration',
 '.',
 'along',
 'with',
 'differentiation',
 ',',
 'integration',
 'is',
 'a',
 'fundamental',
 ',',
 'essential',
 'operation',
 'of',
 'calculus',
 ',',
 '[',
 'a',
 ']',
 'and',
 'serves',
 'as',
 'a',
 'tool',
 'to',
 'solve',
 'problems',
 'in',
 'mathematics',
 'and',
 'physics',
 'involving',
 'the',
 'area',
 'of',
 'an',
 'arbitrary',
 'shape',
 ',',
 'the',
 'length',
 'of',
 'a',
 'curve',
 ',',
 'and',
 'the',
 'volume',
 'of',
 'a',
 'solid',
 ',',
 'among',
 'others',
 '.',
 'the',
 'integrals',
 'enumerated',
 'here',
 'are',
 'those',
 'termed',
 'definite',
 'integrals',
 ',',
 'which',
 'ca

In [12]:
?nltk.word_tokenize

In [14]:
?nltk.TreebankWordTokenizer

In [15]:
articles = [nltk.word_tokenize(art) for art in articles]
articles[0][:10]

['in',
 'mathematics',
 ',',
 'an',
 'integral',
 'assigns',
 'numbers',
 'to',
 'functions',
 'in']

In [38]:
stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [20]:
stopwords = set(nltk.corpus.stopwords.words("english"))
# mozna najpierw tokenizowac stopworodsy, zeby miec spojnosc skrotowcow
articles = [[word for word in art if word not in stopwords] for art in articles]
articles[0][:10]

['mathematics',
 ',',
 'integral',
 'assigns',
 'numbers',
 'functions',
 'way',
 'describes',
 'displacement',
 ',']

In [ ]:
# bardzo zle bo funkce pod if wykonujemy mnostwo razy niepotrzebnie:
#[[word for word in art if word not in nltk.corpus.stopwords.words("english") ] for art in articles]

In [23]:
articles[0][:10]

['mathematics',
 ',',
 'integral',
 'assigns',
 'numbers',
 'functions',
 'way',
 'describes',
 'displacement',
 ',']

In [30]:
len(set(articles[0]))

1185

In [26]:
stemmer = nltk.PorterStemmer()
stemmer.stem("mathematics")

'mathemat'

In [28]:
stemmer.stem("mathematically")

'mathemat'

In [31]:
articles = [[stemmer.stem(word) for word in art] for art in articles]

In [32]:
len(set(articles[0]))

942

In [33]:
articles[0]

['mathemat',
 ',',
 'integr',
 'assign',
 'number',
 'function',
 'way',
 'describ',
 'displac',
 ',',
 'area',
 ',',
 'volum',
 ',',
 'concept',
 'aris',
 'combin',
 'infinitesim',
 'data',
 '.',
 'process',
 'find',
 'integr',
 'call',
 'integr',
 '.',
 'along',
 'differenti',
 ',',
 'integr',
 'fundament',
 ',',
 'essenti',
 'oper',
 'calculu',
 ',',
 '[',
 ']',
 'serv',
 'tool',
 'solv',
 'problem',
 'mathemat',
 'physic',
 'involv',
 'area',
 'arbitrari',
 'shape',
 ',',
 'length',
 'curv',
 ',',
 'volum',
 'solid',
 ',',
 'among',
 'other',
 '.',
 'integr',
 'enumer',
 'term',
 'definit',
 'integr',
 ',',
 'interpret',
 'sign',
 'area',
 'region',
 'plane',
 'bound',
 'graph',
 'given',
 'function',
 'two',
 'point',
 'real',
 'line',
 '.',
 'convent',
 ',',
 'area',
 'horizont',
 'axi',
 'plane',
 'posit',
 'area',
 'neg',
 '.',
 'integr',
 'also',
 'refer',
 'concept',
 'antideriv',
 ',',
 'function',
 'whose',
 'deriv',
 'given',
 'function',
 '.',
 'case',
 ',',
 'call',
 'in

In [34]:
articles = [" ".join(art) for art in articles]
articles[0]

"mathemat , integr assign number function way describ displac , area , volum , concept aris combin infinitesim data . process find integr call integr . along differenti , integr fundament , essenti oper calculu , [ ] serv tool solv problem mathemat physic involv area arbitrari shape , length curv , volum solid , among other . integr enumer term definit integr , interpret sign area region plane bound graph given function two point real line . convent , area horizont axi plane posit area neg . integr also refer concept antideriv , function whose deriv given function . case , call indefinit integr . fundament theorem calculu relat definit integr differenti provid method comput definit integr function antideriv known . although method calcul area volum date ancient greek mathemat , principl integr formul independ isaac newton gottfri wilhelm leibniz late 17th centuri , thought area curv infinit sum rectangl infinitesim width . bernhard riemann later gave rigor definit integr , base limit p

In [36]:
import string
table = str.maketrans({key: None for key in string.punctuation})
articles = [a.translate(table) for a in articles]

In [37]:
articles

['mathemat  integr assign number function way describ displac  area  volum  concept aris combin infinitesim data  process find integr call integr  along differenti  integr fundament  essenti oper calculu    serv tool solv problem mathemat physic involv area arbitrari shape  length curv  volum solid  among other  integr enumer term definit integr  interpret sign area region plane bound graph given function two point real line  convent  area horizont axi plane posit area neg  integr also refer concept antideriv  function whose deriv given function  case  call indefinit integr  fundament theorem calculu relat definit integr differenti provid method comput definit integr function antideriv known  although method calcul area volum date ancient greek mathemat  principl integr formul independ isaac newton gottfri wilhelm leibniz late 17th centuri  thought area curv infinit sum rectangl infinitesim width  bernhard riemann later gave rigor definit integr  base limit procedur approxim area curvi

In [42]:
from sklearn.feature_extraction.text import CountVectorizer
?CountVectorizer

In [44]:
vectorizer = CountVectorizer(token_pattern='(?u)\\b\\w+\\b', min_df=3)
vectorizer.fit(articles)
X = vectorizer.transform(articles)
X

<11x1588 sparse matrix of type '<class 'numpy.int64'>'
	with 7420 stored elements in Compressed Sparse Row format>

In [48]:
vectorizer.get_feature_names() #

['0',
 '1',
 '10',
 '100',
 '101',
 '102',
 '103',
 '104',
 '105',
 '106',
 '107',
 '108',
 '109',
 '11',
 '110',
 '111',
 '112',
 '113',
 '114',
 '115',
 '116',
 '117',
 '118',
 '119',
 '12',
 '120',
 '121',
 '122',
 '123',
 '124',
 '125',
 '126',
 '127',
 '128',
 '129',
 '13',
 '130',
 '131',
 '132',
 '133',
 '134',
 '135',
 '136',
 '14',
 '140',
 '141',
 '142',
 '147',
 '148',
 '149',
 '15',
 '150',
 '151',
 '152',
 '155',
 '156',
 '157',
 '158',
 '159',
 '16',
 '160',
 '161',
 '162',
 '163',
 '164',
 '165',
 '166',
 '167',
 '168',
 '169',
 '17',
 '170',
 '171',
 '172',
 '173',
 '174',
 '175',
 '176',
 '177',
 '178',
 '179',
 '18',
 '180',
 '181',
 '1819',
 '182',
 '183',
 '184',
 '185',
 '1851',
 '1854',
 '1857',
 '186',
 '1860',
 '1861',
 '1862',
 '1863',
 '1864',
 '1868',
 '1869',
 '187',
 '1870',
 '1872',
 '1874',
 '1877',
 '1878',
 '1879',
 '188',
 '1882',
 '1883',
 '1884',
 '1886',
 '1887',
 '1889',
 '189',
 '1890',
 '1891',
 '1892',
 '1893',
 '1894',
 '1895',
 '1896',
 '1898'

In [ ]:
# warto zgrupować liczby np. względem liczby cyfr

In [50]:
X[3,5]

0

In [52]:
X[3]

<1x1588 sparse matrix of type '<class 'numpy.int64'>'
	with 390 stored elements in Compressed Sparse Row format>

In [53]:
X[:,3]

<11x1 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [57]:
import numpy as np

In [66]:
X[:,3].todense()

matrix([[0],
        [0],
        [0],
        [0],
        [0],
        [4],
        [3],
        [0],
        [0],
        [2],
        [1]])

In [65]:
X[:,3].A.flatten()

array([0, 0, 0, 0, 0, 4, 3, 0, 0, 2, 1])

In [72]:
X[:,vectorizer.get_feature_names().index("paint")].todense()

matrix([[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [ 68],
        [125],
        [ 20],
        [  0],
        [  0],
        [  4]])

Podaj 10 najczęstszych słów dla każdego dokumentu.
(argsort)

In [85]:
k = 10
i = 0

words = np.array(vectorizer.get_feature_names())
for i in range(X.shape[0]):
    print(words[X[i].A.flatten().argsort()[::-1]][:10])

['integr' 'function' 'x' 'f' 'b' 'use' 'area' 'interv' 'sum' 'riemann']
['integr' 'riemann' '1' 'x' 'function' 'sum' 'ε' 'interv' 'partit' 'f']
['integr' 'g' 'x' 'displaystyl' 'riemann' 'f' 'function' 'b' 'gener' 'p']
['deriv' 'f' 'function' 'x' 'n' 'point' 'vector' 'r' 'v' 'differenti']
['n' 'x' 'displaystyl' 'sequenc' 'limit' 'b' '1' '0' 'to' 'f']
['s' 'paint' 'museum' 'work' 'art' '1' '4' 'life' 'oil' 'exhibit']
['s' 'paint' 'work' 'art' 'museum' 'pari' 'artist' 'two' '1890' '1889']
['paint' 's' 'art' 'histor' '2' 'nation' '30' 'work' 'histori' 'fine']
['s' 'work' 'war' 'also' 'wrote' 'novel' 'state' 'one' 'peac' 'time']
['s' 'work' 'publish' 'stori' 'write' 'german' 'der' 'die' 'franz' 'time']
['s' 'work' 'languag' 'english' 'publish' 'book' 'first' 'later' 'letter'
 'year']


In [ ]:
# literka s prawdopodobnie zostało z odzielonych "'s" - wypadąłoby poprawić obróbke

In [ ]:
mam

In [86]:
from sklearn.feature_extraction.text import TfidfVectorizer
?TfidfVectorizer

In [90]:
vectorizer = TfidfVectorizer(token_pattern='(?u)\\b\\w+\\b')
vectorizer.fit(articles)
X = vectorizer.transform(articles)

k = 7

words = np.array(vectorizer.get_feature_names())
for i in range(X.shape[0]):
    print(words[X[i].A.flatten().argsort()[::-1]][:k])

['integr' 'function' 'x' 'f' 'b' 'interv' 'riemann']
['integr' 'riemann' 'x' 'interv' 'ε' 'partit' 'sum']
['g' 'integr' 'x' 'riemann' 'displaystyl' 'stieltj' 'f']
['deriv' 'f' 'function' 'x' 'vector' 'differenti' 'v']
['n' 'x' 'displaystyl' 'sequenc' 'limit' 'b' 'lim']
['munch' 'cm' 'oslo' 'paint' 'museum' 's' 'scream']
['van' 'gogh' 'paint' 'theo' 's' 'vincent' '1888']
['matejko' 'kraków' 'polish' 'paint' 'jan' 'histor' 'poland']
['tolstoy' 's' 'russian' 'war' 'anarchist' 'gandhi' 'soviet']
['kafka' 's' 'brod' 'work' 'stori' 'franz' 'publish']
['tolkien' 'lord' 's' 'ring' 'edith' 'hobbit' 'english']


In [92]:
from sklearn.datasets import fetch_20newsgroups

categories = ['alt.atheism', 
              'talk.religion.misc',
              'comp.graphics', 
              'sci.space']
newsgroups_train = fetch_20newsgroups(subset='train', 
                                      categories=categories)

In [94]:
texts = newsgroups_train.data
y = newsgroups_train.target

In [95]:
y

array([1, 3, 2, ..., 1, 0, 1])

In [98]:
print(texts[1])

Subject: Re: Biblical Backing of Koresh's 3-02 Tape (Cites enclosed)
From: kmcvay@oneb.almanac.bc.ca (Ken Mcvay)
Organization: The Old Frog's Almanac
Lines: 20

In article <20APR199301460499@utarlg.uta.edu> b645zaw@utarlg.uta.edu (stephen) writes:

>Seems to me Koresh is yet another messenger that got killed
>for the message he carried. (Which says nothing about the 

Seems to be, barring evidence to the contrary, that Koresh was simply
another deranged fanatic who thought it neccessary to take a whole bunch of
folks with him, children and all, to satisfy his delusional mania. Jim
Jones, circa 1993.

>In the mean time, we sure learned a lot about evil and corruption.
>Are you surprised things have gotten that rotten?

Nope - fruitcakes like Koresh have been demonstrating such evil corruption
for centuries.
-- 
The Old Frog's Almanac - A Salute to That Old Frog Hisse'f, Ryugen Fisher 
     (604) 245-3205 (v32) (604) 245-4366 (2400x4) SCO XENIX 2.3.2 GT 
  Ladysmith, British Columbia, CA

In [99]:
len(texts)

2034

In [101]:
texts_preprocessed = [nltk.word_tokenize(mail) for mail in texts]

stemmer = nltk.PorterStemmer()
texts_preprocessed = [[stemmer.stem(word) for word in mail] for mail in texts_preprocessed]

texts_preprocessed = [" ".join(mail) for mail in texts_preprocessed]

In [103]:
print(texts_preprocessed[0])

from : rych @ festival.ed.ac.uk ( r hawk ) subject : 3d : where did all the textur rule go ? line : 21 hi , i 've notic that if you onli save a model ( with all your map plane posit care ) to a .3d file that when you reload it after restart 3d , they are given a default posit and orient . but if you save to a .prj file their positions/orient are preserv . doe anyon know whi thi inform is not store in the .3d file ? noth is explicitli said in the manual about save textur rule in the .prj file . i 'd like to be abl to read the textur rule inform , doe anyon have the format for the .prj file ? is the .cel file format avail from somewher ? rych ====================================================================== rychard hawk email : rych @ festival.ed.ac.uk virtual environ laboratori dept . of psycholog tel : +44 31 650 3426 univ . of edinburgh fax : +44 31 667 0150 ======================================================================


In [104]:
vectorizer = TfidfVectorizer()
vectorizer.fit(texts_preprocessed)
X = vectorizer.transform(texts_preprocessed)
words = np.array(vectorizer.get_feature_names())

In [112]:
k = 7
i = 500
print(words[X[i].A.flatten().argsort()[::-1]][:k])
print("")
print(texts[i])

['drickel' 'mentorg' 'bounce' 'rickel' 'mcelwain' 'unit' 'aa49462']

From: drickel@bounce.mentorg.com (Dave Rickel)
Subject: Re: So I'm an idiot, what else is new?
Originator: drickel@bounce
Nntp-Posting-Host: bounce.mentorg.com
Organization: Mentor Graphics 
Keywords: 
Lines: 17


In article <9303311213.AA49462@jsc.nasa.gov>, mcelwre@cnsvax.uwec.edu (R. E. McElwaine) writes:
|> RUSSIA'S OPERATIVE
|> 
|>                In March 1993, Russian President Boris Yeltsin
|>           proposed to the United States and the United Nations a global
|>           defense shield (with "Star Wars"-type weapons) AGAINST
...

Funny.  A bit disturbing.  Forging a posting seems somewhat unethical, even
if the subject is as notorious as McElwaine.

Followups should definitely not go to sci.space.


david rickel
drickel@sjc.mentorg.com



In [113]:
vectorizer = TfidfVectorizer(token_pattern='(?u)\\b\\w+\\b')
vectorizer.fit(articles)
X = vectorizer.transform(articles)
X

<11x6790 sparse matrix of type '<class 'numpy.float64'>'
	with 13620 stored elements in Compressed Sparse Row format>

In [114]:
from sklearn.decomposition import TruncatedSVD

LSI:

In [116]:
dim_reductor = TruncatedSVD(3)
dim_reductor.fit(X)
dim_reductor.transform(X).round(2)

array([[ 0.83, -0.03,  0.01],
       [ 0.84, -0.06, -0.01],
       [ 0.84, -0.07, -0.01],
       [ 0.61, -0.01,  0.01],
       [ 0.54, -0.04, -0.01],
       [ 0.07,  0.54, -0.4 ],
       [ 0.06,  0.57, -0.37],
       [ 0.05,  0.54, -0.28],
       [ 0.05,  0.42,  0.45],
       [ 0.05,  0.42,  0.49],
       [ 0.06,  0.42,  0.44]])